services:
  igen-insightface:
    image: ghcr.io/chung2310/server-face:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-igen-insightface}
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
      - ${MODEL_DIR:-/opt/igen-insightface/models}:/root/.insightface
    networks:
      - default_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default_network:
    external: true
